import Head from 'next/head';
import Header from '../components/Header';
import Listing from '../components/Listing';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container px-5 md:px-10">
        <Header />
        <Listing />
      </main>
    </div>
  );
}
